In [ ]:
import numpy as np


# ============================================================
# Problem 2: Image Memory
# ============================================================
# Calculate how much memory is required to store an image.


# ============================================================
# Step 1: Inputs and Outputs
# ============================================================
# Input:
# Width of the image in pixels
# Height of the image in pixels
# Bits per pixel (bpp)
#
# Output:
# Memory required by the image in bytes.


# ============================================================
# Step 2: Mathematical Rule
# ============================================================
#
# Formula:
#
# Memory (bytes) = width * height * bpp / 8
#
# We divide by 8 because:
#
# 8 bits = 1 byte


# ============================================================
# Step 3: Manual Trace
# ============================================================

# Example:
#
# Width  = 1920 pixels
# Height = 1080 pixels
# BPP    = 24 bits per pixel
#
# First calculate the total number of bits:
#
# Total bits = 1920 * 1080 * 24
#            = 49,766,400 bits
#
# Convert bits into bytes:
#
# Memory = 49,766,400 / 8
#        = 6,220,800 bytes
#
# Therefore:
#
# Image Memory = 6,220,800 bytes


# ============================================================
# Step 4: Python
# ============================================================

def display_memory_bytes(width: int, height: int, bpp: int) -> int:
    """Return image memory in bytes."""

    # Calculate total memory in bytes
    memory = width * height * bpp // 8

    return memory


# ============================================================
# Input Values
# ============================================================

width = 1920
height = 1080
bpp = 24


# ============================================================
# Calculate Memory
# ============================================================

memory = display_memory_bytes(
    width,
    height,
    bpp
)


# ============================================================
# Display Result
# ============================================================

print("Image Width:", width)
print("Image Height:", height)
print("Bits Per Pixel:", bpp)
print("Image Memory:", memory, "bytes")


# ============================================================
# Test
# ============================================================

expected_bytes = 1920 * 1080 * 24 // 8

assert display_memory_bytes(
    1920,
    1080,
    24
) == expected_bytes

print("\nProblem 2 passed")

Input Image:
[[ 20 128 200]
 [100 150 250]]

Threshold: 128

Output Image:
[[  0 255 255]
 [  0 255 255]]

Problem 1 passed
