In [ ]:
import numpy as np


# ============================================================
# Problem 5: Find an Edge with Sobel
# ============================================================
# Use a Sobel filter to find how strong an edge is
# in the middle of a 3 x 3 grayscale block.


# ============================================================
# Step 1: Inputs and Outputs
# ============================================================
# Input:
# A 3 x 3 grayscale image block with pixel values from 0 to 255.
#
# Output:
# gx  = horizontal edge response
# gy  = vertical edge response
# strength = overall edge strength


# ============================================================
# Step 2: Mathematical Rule
# ============================================================

# Sobel Gx kernel:
#
# -1   0   1
# -2   0   2
# -1   0   1
#
# Sobel Gy kernel:
#
# -1  -2  -1
#  0   0   0
#  1   2   1
#
# Formula:
#
# gx = sum(block * Gx)
# gy = sum(block * Gy)
#
# Edge strength:
#
# strength = sqrt(gx^2 + gy^2)


# ============================================================
# Step 3: Manual Trace
# ============================================================

# Example input:
#
# [20   20  200]
# [20   20  200]
# [20   20  200]
#
# Calculate Gx:
#
# gx = (20*-1) + (20*0) + (200*1)
#    + (20*-2) + (20*0) + (200*2)
#    + (20*-1) + (20*0) + (200*1)
#
# gx = -20 + 200 - 40 + 400 - 20 + 200
# gx = 720
#
# Calculate Gy:
#
# gy = (20*-1) + (20*-2) + (200*-1)
#    + (20*0) + (20*0) + (200*0)
#    + (20*1) + (20*2) + (200*1)
#
# gy = -20 - 40 - 200 + 20 + 40 + 200
# gy = 0
#
# Edge strength:
#
# strength = sqrt(720^2 + 0^2)
#          = sqrt(518400)
#          = 720
#
# Therefore:
#
# gx = 720
# gy = 0
# edge strength = 720


# ============================================================
# Step 4: Python
# ============================================================

def sobel_response(block: np.ndarray) -> tuple[float, float, float]:
    """Return gx, gy, and edge strength."""

    # Sobel Gx kernel
    gx_kernel = np.array(
        [
            [-1, 0, 1],
            [-2, 0, 2],
            [-1, 0, 1]
        ],
        dtype=np.float32
    )

    # Sobel Gy kernel
    gy_kernel = np.array(
        [
            [-1, -2, -1],
            [0, 0, 0],
            [1, 2, 1]
        ],
        dtype=np.float32
    )

    # Calculate horizontal edge response
    gx = float(np.sum(block * gx_kernel))

    # Calculate vertical edge response
    gy = float(np.sum(block * gy_kernel))

    # Calculate overall edge strength
    strength = float(np.sqrt(gx * gx + gy * gy))

    return gx, gy, strength


# ============================================================
# Input 3 x 3 Image Block
# ============================================================

problem_5_input = np.array(
    [
        [20, 20, 200],
        [20, 20, 200],
        [20, 20, 200]
    ],
    dtype=np.float32
)


# ============================================================
# Calculate Sobel Response
# ============================================================

gx, gy, strength = sobel_response(problem_5_input)


# ============================================================
# Display Input and Results
# ============================================================

print("Input 3x3 Image:")
print(problem_5_input)

print("\nGx:", gx)
print("Gy:", gy)
print("Edge Strength:", strength)


# ============================================================
# Test
# ============================================================

assert gx == 720.0
assert gy == 0.0
assert strength == 720.0

print("\nProblem 5 passed")