In [ ]:
import numpy as np


# ============================================================
# Problem 3: Average 9 Pixels
# ============================================================
# Find the rounded average of a 3 x 3 image block.


# ============================================================
# Step 1: Inputs and Outputs
# ============================================================
# Input:
# Nine pixel values arranged in a 3 x 3 grayscale image block.
#
# Output:
# One rounded integer representing the average
# of all 9 pixel values.


# ============================================================
# Step 2: Mathematical Rule
# ============================================================
#
# Formula:
#
# Average = Sum of all 9 pixel values / 9
#
# After calculating the average, round the result
# to the nearest integer.


# ============================================================
# Step 3: Manual Trace
# ============================================================

# Example:
#
# [10   20   10]
# [30   50   30]
# [10   20   10]
#
# First, calculate the sum:
#
# Sum = 10 + 20 + 10
#     + 30 + 50 + 30
#     + 10 + 20 + 10
#
# Sum = 190
#
# Now calculate the average:
#
# Average = 190 / 9
#         = 21.11
#
# Round the answer:
#
# Rounded Average = 21
#
# Therefore, the final answer is:
#
# 21


# ============================================================
# Step 4: Python
# ============================================================

def mean_filter_3x3(neighborhood: np.ndarray) -> int:
    """Return the rounded average of 9 pixels."""

    # Calculate the sum of all 9 pixels
    total = np.sum(neighborhood)

    # Calculate the average
    average = total / 9

    # Round the average and convert it to integer
    return int(round(average))


# ============================================================
# Input 3 x 3 Image Block
# ============================================================

problem_3_input = np.array(
    [
        [10, 20, 10],
        [30, 50, 30],
        [10, 20, 10]
    ],
    dtype=np.uint8
)


# ============================================================
# Calculate Average
# ============================================================

average = mean_filter_3x3(problem_3_input)


# ============================================================
# Display Input and Output
# ============================================================

print("Input 3x3 Image:")
print(problem_3_input)

print("\nAverage of 9 pixels:", average)


# ============================================================
# Test
# ============================================================

assert mean_filter_3x3(problem_3_input) == 21

print("\nProblem 3 passed")