In [5]:
import numpy as np


# ============================================================
# Problem 1: Image Thresholding
# ============================================================
# Convert a grayscale image into a binary image using
# a threshold value.


# ============================================================
# Step 1: Inputs and Outputs
# ============================================================
# Input:
# A grayscale image containing pixel values.
# A threshold value.
#
# Output:
# A binary image where:
# pixels >= threshold become 255
# pixels < threshold become 0


# ============================================================
# Step 2: Mathematical Rule
# ============================================================
#
# For every pixel:
#
# If pixel >= threshold:
#       output = 255
#
# Otherwise:
#       output = 0
#
# In this problem:
#
# threshold = 128


# ============================================================
# Step 3: Manual Trace
# ============================================================

# Input image:
#
# [ 20   128   200]
# [100   150   250]
#
# Threshold = 128
#
# Check each pixel:
#
# 20  < 128  -> 0
# 128 >= 128 -> 255
# 200 >= 128 -> 255
# 100 < 128  -> 0
# 150 >= 128 -> 255
# 250 >= 128 -> 255
#
# Therefore, the output is:
#
# [0   255   255]
# [0   255   255]


# ============================================================
# Step 4: Python
# ============================================================

def threshold_image(
    image: np.ndarray,
    threshold: int
) -> np.ndarray:
    """Convert a grayscale image into a binary image."""

    # Pixels greater than or equal to threshold become 255.
    # Pixels below threshold become 0.
    result = np.where(
        image >= threshold,
        255,
        0
    )

    return result.astype(np.uint8)


# ============================================================
# Input Image
# ============================================================

image = np.array(
    [
        [20, 128, 200],
        [100, 150, 250]
    ],
    dtype=np.uint8
)


# ============================================================
# Threshold Value
# ============================================================

threshold = 128


# ============================================================
# Apply Thresholding
# ============================================================

output = threshold_image(
    image,
    threshold
)


# ============================================================
# Display Input and Output
# ============================================================

print("Input Image:")
print(image)

print("\nThreshold:", threshold)

print("\nOutput Image:")
print(output)


# ============================================================
# Test
# ============================================================

expected = np.array(
    [
        [0, 255, 255],
        [0, 255, 255]
    ],
    dtype=np.uint8
)

np.testing.assert_array_equal(
    output,
    expected
)

print("\nProblem 1 passed")

Input Image:
[[ 20 128 200]
 [100 150 250]]

Threshold: 128

Output Image:
[[  0 255 255]
 [  0 255 255]]

Problem 1 passed
